### ISSUE TITLE
Question: How would you test the "Todos" component ?

### ISSUE THREAD

**Issue by atomrc** [cyclejs/todomvc-cycle#29]
Hi, I am new to cyclejs and Rx and, even if it completely twists my brain, I love it. 

I am currently having a little problem with testing my components. 
The case of a small independent component is, indeed, very easy to test. Simulating user interactions with the `mockDOMSource` cannot be easier :)
But when I am dealing with nested components, I am not sure how to do that in a nice clean way. 

The case I am dealing with, is exactly the case of the `Todos` component in this repo. I have a component that renders a list of instances of a smaller component (eg the `TodoItem`). I don't really know how to test the `destroy` action for example. 

The idea I came up with (which I am not very satisfied of) is **to "publish"\* the different part of the component (intent, model, view)** and test every different aspect of the component separately. Then you can easily send action streams to the "model" part without having to mock user interactions. 

The thing is, I like to think of my components as complete black boxes and it doesn't feel right to give "public" access to the different parts of the component.

So, I am asking you the question: **how would you test the destroy action (or any other action from `TotoItem` that has consequence on the `Todos` component) ?**

Thanks :)

*: publish might not be the correct word for it. When I say publish, I mean, either, exporting it in the component's module or splitting it in a separate module file so it can be imported latter on.

**Comment by Cmdv** [comment]
@atomrc I hadn't got round to doing the test but [here](https://github.com/Cmdv/cycle-webpack-boilerplate/tree/master/src/dialogue/pages/home) you can see how I seperated my component/page MVI into seperate files.

now they would each become pure functions that you could easily with your given inputs and seeing if you get the outputs you expect.

I hope this is enough help sorry I can't be more precise but feel free to also ask on the [gitter channel](https://gitter.im/cyclejs/core) if you have code examples you want people to look at and help :smiley:

**Comment by atomrc** [comment]
Thanks for your answer @Cmdv :)

Splitting the parts (MVI) of the component into separate modules was, indeed, the idea I had to easily test a component. But, I have to admit, I am not found of the idea to "give access" to the internals of the component. 

I think when you have a logic that needs to be shared between components, then it is normal for it to have it's own module, But in the case of a component, which I see as a complete black box, then it feels weird. 

Anyway I might be thinking the wrong way here, splitting into modules might very well be the right way to test components :)

**Comment by Cmdv** [comment]
@atomrc they are just inner parts of the module, they really shouldn't care about what is happening externally and if you take a look at [index.js](https://github.com/Cmdv/cycle-webpack-boilerplate/blob/master/src/dialogue/pages/home/home-index.js#L6-L15) you will see this is where I set up all of these parts so you get an even better idea of what is happening.

Think of the parts as cogs inside the box and that allows you to test each cog so to speak.

You can easily mock each one with your own custom streams, say a really simple DOM stream for your intent. Then we you test you are really isolating your test down to a component.

This comes about because of Functional Programming concepts where these cogs should be pure functions. The basics is that given you put the same input you will always get the same output. The inner workings of that function aren't dealt internally and shouldn't call external state to run. You might be aware of all this so sorry if you are but otherwise take a look at [this book](https://drboolean.gitbooks.io/mostly-adequate-guide/content/) for some interesting concepts :smiley:

**Comment by atomrc** [comment]
I am very aware of functional programming and pure function :) This is, in fact, what convinced me to seriously try Cycle and honestly, I am not disappointed!

It was nice to have you advice @Cmdv I guess I'll stick with testing each part of the component separately. Sounds good to me. 

Thanks again @Cmdv
